# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createvm.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblVMName = QtWidgets.QLabel(self.centralwidget)
        self.lblVMName.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.lblVMName.setObjectName("lblVMName")
        self.leName = QtWidgets.QLineEdit(self.centralwidget)
        self.leName.setGeometry(QtCore.QRect(70, 30, 351, 25))
        self.leName.setObjectName("leName")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(100, 70, 256, 192))
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblVMName.setText(_translate("MainWindow", "Name"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "ArchLinux"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "ArchLinux 64"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Debian"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Debian 64"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "DOS"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Fedora"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Fedora 64"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "FreeBSD"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "FreeBSD 64"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "Gentoo"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "Gentoo 64"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "JRockitVE"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "L4"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "Linux 2.2"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "Linux 2.4"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "Linux 2.4 64"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "Linux 2.6"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "Linux 2.6 64"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "Mac OS"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "MacOSX 10.10 64"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "MacOSX 10.11 64"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "MacOSX 10.12 64"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "MacOSX 10.13 64"))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "MacOSX 10.6"))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "MacOSX 10.6 64"))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "MacOSX 10.7"))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "MacOSX 10.7 64"))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "MacOSX 10.8"))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", "MacOSX 10.8 64"))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", "MacOSX 10.9"))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "MacOSX 10.9 64"))
        item = self.listWidget.item(31)
        item.setText(_translate("MainWindow", "MacOSX 64"))
        item = self.listWidget.item(32)
        item.setText(_translate("MainWindow", "Mandriva"))
        item = self.listWidget.item(33)
        item.setText(_translate("MainWindow", "Mandriva 64"))
        item = self.listWidget.item(34)
        item.setText(_translate("MainWindow", "NetBSD"))
        item = self.listWidget.item(35)
        item.setText(_translate("MainWindow", "NetBSD 64"))
        item = self.listWidget.item(36)
        item.setText(_translate("MainWindow", "Netware"))
        item = self.listWidget.item(37)
        item.setText(_translate("MainWindow", "OpenBSD"))
        item = self.listWidget.item(38)
        item.setText(_translate("MainWindow", "OpenBSD 64"))
        item = self.listWidget.item(39)
        item.setText(_translate("MainWindow", "OpenSolaris"))
        item = self.listWidget.item(40)
        item.setText(_translate("MainWindow", "OpenSolaris 64"))
        item = self.listWidget.item(41)
        item.setText(_translate("MainWindow", "OpenSUSE"))
        item = self.listWidget.item(42)
        item.setText(_translate("MainWindow", "OpenSUSE 64"))
        item = self.listWidget.item(43)
        item.setText(_translate("MainWindow", "Oracle"))
        item = self.listWidget.item(44)
        item.setText(_translate("MainWindow", "Oracle 64"))
        item = self.listWidget.item(45)
        item.setText(_translate("MainWindow", "OS2"))
        item = self.listWidget.item(46)
        item.setText(_translate("MainWindow", "OS21x"))
        item = self.listWidget.item(47)
        item.setText(_translate("MainWindow", "OS2eCS"))
        item = self.listWidget.item(48)
        item.setText(_translate("MainWindow", "OS2Warp3"))
        item = self.listWidget.item(49)
        item.setText(_translate("MainWindow", "OS2Warp4"))
        item = self.listWidget.item(50)
        item.setText(_translate("MainWindow", "OS2Warp4.5"))
        item = self.listWidget.item(51)
        item.setText(_translate("MainWindow", "Other"))
        item = self.listWidget.item(52)
        item.setText(_translate("MainWindow", "Other 64"))
        item = self.listWidget.item(53)
        item.setText(_translate("MainWindow", "QNX"))
        item = self.listWidget.item(54)
        item.setText(_translate("MainWindow", "RadHat"))
        item = self.listWidget.item(55)
        item.setText(_translate("MainWindow", "RedHat 64"))
        item = self.listWidget.item(56)
        item.setText(_translate("MainWindow", "Solaris"))
        item = self.listWidget.item(57)
        item.setText(_translate("MainWindow", "Solaris 11"))
        item = self.listWidget.item(58)
        item.setText(_translate("MainWindow", "Solaris 64"))
        item = self.listWidget.item(59)
        item.setText(_translate("MainWindow", "Turbolinux"))
        item = self.listWidget.item(60)
        item.setText(_translate("MainWindow", "Turbolinux 64"))
        item = self.listWidget.item(61)
        item.setText(_translate("MainWindow", "Ubuntu"))
        item = self.listWidget.item(62)
        item.setText(_translate("MainWindow", "Ubuntu 64"))
        item = self.listWidget.item(63)
        item.setText(_translate("MainWindow", "VBoxBS_64Windows10"))
        item = self.listWidget.item(64)
        item.setText(_translate("MainWindow", "Windows10_64"))
        item = self.listWidget.item(65)
        item.setText(_translate("MainWindow", "Windows 2000"))
        item = self.listWidget.item(66)
        item.setText(_translate("MainWindow", "Windows 2003"))
        item = self.listWidget.item(67)
        item.setText(_translate("MainWindow", "Windows 2008"))
        item = self.listWidget.item(68)
        item.setText(_translate("MainWindow", "Windows 2012 64"))
        item = self.listWidget.item(69)
        item.setText(_translate("MainWindow", "Windows 2016 64"))
        item = self.listWidget.item(70)
        item.setText(_translate("MainWindow", "Windows 3.1"))
        item = self.listWidget.item(71)
        item.setText(_translate("MainWindow", "Windows 7"))
        item = self.listWidget.item(72)
        item.setText(_translate("MainWindow", "Windows 7 64"))
        item = self.listWidget.item(73)
        item.setText(_translate("MainWindow", "Windows 8"))
        item = self.listWidget.item(74)
        item.setText(_translate("MainWindow", "Windows 8 64"))
        item = self.listWidget.item(75)
        item.setText(_translate("MainWindow", "Windows 8.1"))
        item = self.listWidget.item(76)
        item.setText(_translate("MainWindow", "Windows 8.1 64"))
        item = self.listWidget.item(77)
        item.setText(_translate("MainWindow", "Windows 95"))
        item = self.listWidget.item(78)
        item.setText(_translate("MainWindow", "Windows 98"))
        item = self.listWidget.item(79)
        item.setText(_translate("MainWindow", "Windows Me"))
        item = self.listWidget.item(80)
        item.setText(_translate("MainWindow", "Windows NT"))
        item = self.listWidget.item(81)
        item.setText(_translate("MainWindow", "Windows NT 3x"))
        item = self.listWidget.item(82)
        item.setText(_translate("MainWindow", "Windows NT 4"))
        item = self.listWidget.item(83)
        item.setText(_translate("MainWindow", "Windows NT 64"))
        item = self.listWidget.item(84)
        item.setText(_translate("MainWindow", "Windows Vista"))
        item = self.listWidget.item(85)
        item.setText(_translate("MainWindow", "Windows Vista 64"))
        item = self.listWidget.item(86)
        item.setText(_translate("MainWindow", "Windows XP"))
        item = self.listWidget.item(87)
        item.setText(_translate("MainWindow", "Windows XP 64"))
        item = self.listWidget.item(88)
        item.setText(_translate("MainWindow", "Xandros"))
        item = self.listWidget.item(89)
        item.setText(_translate("MainWindow", "Xandros 64"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

